### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by imawhale** [StefMa/hugo-fresh#101]
I am deploying on netlify - what build directory should I specify in netlify.toml?

I deployed another theme using "/public" but there is no public dir in this theme.

Thanks!

**Comment by StefMa** [comment]
I am not a netlify user so I can't help your here.
But at the end it is simply static code. You only have tun run "Hugo" on
your command line. Then there will be an public directory which can be
deployed...

**Comment by imawhale** [comment]
In case anyone else has this issue, here is my netlify.toml, which now works. 

Thanks for a great theme!

`[build]
publish = "public"
command = "hugo"
#command = "hugo --gc --minify"
[context.production.environment]
HUGO_VERSION = "0.60.1"
#HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.60.1"
#HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.60.1"
#HUGO_VERSION = "0.54.0"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.60.1"
#HUGO_VERSION = "0.54.0"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
`
