### ISSUE TITLE
Insert external link to clientlogos

### ISSUE THREAD

**Issue by quybaohoang** [StefMa/hugo-fresh#104]
Hello,

How can I insert link to each image of client logos? I want to link each image to an external url.

Thank you so much,

**Comment by StefMa** [comment]
I guess this is not possible atm. But nice feature request.
I will take a deeper look at it tomorrow and get back to the issue
afterwards.

**Comment by StefMa** [comment]
I just looked over it and unfortunately it is not possible atm.
[This is the html](https://github.com/StefMa/hugo-fresh/blob/5ebe24e941484f51dfe9638bd6011c5004ac49db/layouts/partials/hero-footer.html) which renders the logos.
As you see there are only the "clientlogos" params which are rendered. Without any links or something.

But I think this could be a nice feature.
I suggest that we add something like this tot he config:
```diff
-    clientlogos:
-    - systek
-    - tribe
-    - kromo
-    - infinite
-    - gutwork

+    clientlogos:
+    - logo: systek
+      url: https://www...
+    - logo: tribe
+      url: https://www...
+    - logo: kromo
+      url: https://www...
+    - logo: infinite
+      url: https://www...
+    - logo: gutwork
+      url: https://www...
```

**Comment by quybaohoang** [comment]
Sounds great!
