### ISSUE TITLE
Navbar link to section4

### ISSUE THREAD

**Issue by Seljo34** [StefMa/hugo-fresh#107]
It is not clear how to make a link for example from navbar to section 4 ?

**Comment by StefMa** [comment]
Do you want that a click on a navbar icon should scroll to a specific section?

**Comment by Seljo34** [comment]
Yes exactly.

**Comment by Seljo34** [comment]
> Do you want that a click on a navbar icon should scroll to a specific section?

Yes

**Comment by StefMa** [comment]
Yep, I have read this. No reason to answer twice ✌️.

**Comment by rglsk** [comment]
@StefMa @Seljo34 So is this possible to be done from a project config?

**Comment by StefMa** [comment]
I haven't checked that yet. But I guess it is currently not possible and needs to be implemented.

**Comment by rglsk** [comment]
Ok, thanks. Maybe I will add PR later with this feature 👍

**Comment by nimitsolanki** [comment]
@Piotr-Rogulski any update on this? How can we scroll to particular section when a user clicks on the navigation menu?

**Comment by rglsk** [comment]
@nimitsolanki I have not made the update to allow it from config, but for now, as a fast solution you can just update your section Html template with `name={your_anchor_name}` and then link it in the config navbar as `#your_anchor_name`

**Comment by nimitsolanki** [comment]
Thanks for quick response, could you please explain your answer with an example. Thanks

**Comment by rglsk** [comment]
@nimitsolanki 
<img width="435" alt="Screenshot 2020-02-17 at 12 40 20" src="https://user-images.githubusercontent.com/2768101/74650813-cd4a0500-5182-11ea-85db-540269a0a759.png">
<img width="244" alt="Screenshot 2020-02-17 at 12 40 31" src="https://user-images.githubusercontent.com/2768101/74650815-cf13c880-5182-11ea-9eb7-4e7a6a739f78.png">

**Comment by Seljo34** [comment]
> @nimitsolanki
> <img alt="Screenshot 2020-02-17 at 12 40 20" width="435" src="https://user-images.githubusercontent.com/2768101/74650813-cd4a0500-5182-11ea-85db-540269a0a759.png">
> <img alt="Screenshot 2020-02-17 at 12 40 31" width="244" src="https://user-images.githubusercontent.com/2768101/74650815-cf13c880-5182-11ea-9eb7-4e7a6a739f78.png">

I tired this, but the link only loads the homepage without scrolling down to the section.
Do I have to edit something else ?

![config](https://user-images.githubusercontent.com/23176263/74654296-4bf67080-518a-11ea-9418-f03ad6d4b97b.JPG)
![section4](https://user-images.githubusercontent.com/23176263/74654297-4c8f0700-518a-11ea-9d00-bf8028335beb.JPG)

**Comment by nimitsolanki** [comment]
@Piotr-Rogulski It is working for me! I have followed your example. Thanks!

**Comment by StefMa** [comment]
Could someone maybe create a PR with this? Using names as section1, sections2 etc. of course to keep it generic.
I would really appreciate it. Thanks in advance 👌

**Comment by StefMa** [comment]
This is possible since August 2022 🙂 .
Checkout this PR: https://github.com/StefMa/hugo-fresh/pull/139

Now, you can simply add a link to `/#section[1|2|3|4|5]`
