### ISSUE TITLE
Dropdowns in the top menu dont work

### ISSUE THREAD

**Issue by unrealwork** [StefMa/hugo-fresh#11]
https://themes.gohugo.io/theme/hugo-fresh/

**Comment by unrealwork** [comment]
I think you just did not build the latest core.css component, current version contains deprecated `nav-item` class, but you use `navbar-item` in layouts.

**Comment by ericmand** [comment]
I'm seeing this too. It seems as two versions of core are generated but the deprecated one is rendered. Did you figure out how to fix?

**Comment by lucperkins** [comment]
At the moment I'm starting a new job and unfortunately don't really have the bandwidth for this. Please feel free to submit pull requests with fixes.

**Comment by lucperkins** [comment]
@unrealwork @ericmand I've updated the theme to use the new Fresh theme from CSS Ninja, so this should no longer be an issue
