### ISSUE TITLE
how can i get the site

### ISSUE THREAD

**Issue by Despinola1** [StefMa/hugo-fresh#110]
Dear, I would like to be able to get the sample page, if you help me to clone the demo site ..
thanks

**Comment by StefMa** [comment]
There is a getting started section in the Readme.
Doesn't this work for you?

**Comment by Despinola1** [comment]
No dear, I can't get the sample site, please help me?
or sending the site with all the files in a .zip to my email Despinola1@gmail.com

thanks

**Comment by StefMa** [comment]
What problem do you have?
I cannot help you if you just say 'it does not work'... Where do you stuck?

**Comment by lucperkins** [comment]
@Despinola1 This is a theme for the [Hugo](https://gohugo.io) static site generator. If you're not using Hugo then this will not be useful for you.

**Comment by einsts** [comment]
There is a table in a markdown file I wrote, I want my table to have a line border, how should I modify it
