### ISSUE TITLE
Links not working from clone, also not working on the demo site

### ISSUE THREAD

**Issue by chriswiqa** [StefMa/hugo-fresh#111]
On both my clone and the [demo](https://themes.gohugo.io/theme/hugo-fresh/) site, the links are broken resulting in 404.  Example [AGB](https://themes.gohugo.io//theme/hugo-fresh/agb) footer.  Blog links are similar.  I can't see how to determine relative path to resolve.

**Comment by chriswiqa** [comment]
Ok putting pages into the root [website]/content path not the themes/hugo-fresh/exampleSite/content and working for me now...

**Comment by StefMa** [comment]
Hi

I have a "real" demo deployed here:
https://hugo-fresh.now.sh/
