### ISSUE TITLE
Update bulma

### ISSUE THREAD

**Issue by asebold** [StefMa/hugo-fresh#114]
Bulma has made some nice updates over the past year: https://github.com/jgthms/bulma/blob/master/CHANGELOG.md

Currently it appears the theme is using v0.7.0. Would be nice to update to Bulma 0.9.0 to get all the new features.

**Comment by StefMa** [comment]
Now we are using always the latest version of bulma 🚀 
Checkout https://github.com/StefMa/hugo-fresh/pull/134
