### ISSUE TITLE
How can I add Lunr or Algolia search to this theme?

### ISSUE THREAD

**Issue by cells800** [StefMa/hugo-fresh#116]
Is there any way to add Lunr or Algolia search on this theme?

**Comment by todinov** [comment]
Not sure how algolia works, but you can add lunr to any hugo site. I would use a pre-built index from a type template for lunr. So you add a template in `layouts/search/single.html`. Something like:
```
{{ $.Scratch.Add "index" slice }}

{{ $searchablePages := where .Site.Pages "Params.type" "!=" "search" }}

{{ range $index, $page := $searchablePages }}
  {{ .Scratch.Set "pageData" "" }}
  {{ .Scratch.Set "pageContent" "" }}
  {{ .Scratch.Set "pageURL" "" }}
  {{ .Scratch.Set "pageTag" "" }}


  {{ if gt (len $page.Content) 0 }}
    {{ .Scratch.Set "pageContent" $page.Plain }}
    {{ .Scratch.Set "pageURL" $page.Permalink }}
    {{ if (isset $page.Params "tags") }}
    {{ .Scratch.Set "pageTag" (delimit $page.Params.tags " ; ") }}
    {{ end }}

    {{ .Scratch.Set "pageData" (dict "id" $index "title" $page.Title "url" (.Scratch.Get "pageURL") "content" (.Scratch.Get "pageContent") "tag" (.Scratch.Get "pageTag")) }}

    {{ $.Scratch.Add "index" (.Scratch.Get "pageData") }}
  {{ end }}
{{ end }}

{{ $.Scratch.Get "index" | jsonify }}
```
Then you create a placeholder page in your content. `content/search/index.md` for example.
```
---
title: Search
type: search
---

This is a placeholder to serve the search
```

Next you need to place the search field somewhere, maybe in the navbar:
```
<div class="navbar-item" role="search" id="search-wrapper">
    <input type="search" class="input" placeholder="Search" autocomplete="off" id="search-field" disabled="disabled" />

    <div class="navbar-dropdown" id="search-results"></div>
</div>
```

Then a little bit of JS to make it all click. You can copy the javascript.html template in your layouts and add it there.
```
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://unpkg.com/lunr/lunr.js"></script>
<script>
axios.get("/search")
    .then(function (result) {
        var searchContent = result.data;
        var searchIndex = lunr(function () {
            this.ref("id")
            this.field("content");
            this.field("tag");
            this.field("title");
            this.field("url");

            Array.from(result.data).forEach(function (doc) {
                this.add(doc)
            }, this)
        })

        var searchWrapper = document.getElementById("search-wrapper");
        var searchInput = document.getElementById("search-field");
        var searchResultElement = document.getElementById("search-results");

        searchInput.removeAttribute("disabled");
        searchInput.addEventListener("keyup", function (e) {
            var searchString = e.target.value;
            if (searchString && searchString.length > 2) {
                try {
                    searchResults = searchIndex.search(searchString);
                } catch (err) {
                    if (err instanceof lunr.QueryParseError) {
                        return;
                    }
                }
            } else {
                searchResults = [];
            }

            searchWrapper.classList.add("is-active");

            if (searchResults.length > 0) {
                searchResultElement.innerHTML = searchResults.map(function (match) {
                    var item = searchContent.find(function(e) {
                        return e.id == parseInt(match.ref);
                    });

                    return [
                        "<div class='dropdown-item'>",
                        "<h4><a href='" + item.url + "'>" + item.title + "</a></h4>",
                        "<p>" + (item.content.length > 100 ? (item.content.substring(0, 100) + "...") : item.content) + "</p>",
                        "</div>"
                    ].join("");
                }).join("<hr class='navbar-divider'>");
            } else {
                searchResultElement.innerHTML = '<div class="dropdown-item"><p>No results found</p></div>';
            }
        });
    })
    .catch(function (error) {
        console.error(error);
    });

</script>
```
Here I'm using axios for making the http request for the pre-built index, but the theme is using jQuery so I'd recommend to switch to that.
Hope this helps.

**Comment by cells800** [comment]
> Not sure how algolia works, but you can add lunr to any hugo site. I would use a pre-built index from a type template for lunr. So you add a template in `layouts/search/single.html`. Something like:
> 
> ```
> {{ $.Scratch.Add "index" slice }}
> 
> {{ $searchablePages := where .Site.Pages "Params.type" "!=" "search" }}
> 
> {{ range $index, $page := $searchablePages }}
>   {{ .Scratch.Set "pageData" "" }}
>   {{ .Scratch.Set "pageContent" "" }}
>   {{ .Scratch.Set "pageURL" "" }}
>   {{ .Scratch.Set "pageTag" "" }}
> 
> 
>   {{ if gt (len $page.Content) 0 }}
>     {{ .Scratch.Set "pageContent" $page.Plain }}
>     {{ .Scratch.Set "pageURL" $page.Permalink }}
>     {{ if (isset $page.Params "tags") }}
>     {{ .Scratch.Set "pageTag" (delimit $page.Params.tags " ; ") }}
>     {{ end }}
> 
>     {{ .Scratch.Set "pageData" (dict "id" $index "title" $page.Title "url" (.Scratch.Get "pageURL") "content" (.Scratch.Get "pageContent") "tag" (.Scratch.Get "pageTag")) }}
> 
>     {{ $.Scratch.Add "index" (.Scratch.Get "pageData") }}
>   {{ end }}
> {{ end }}
> 
> {{ $.Scratch.Get "index" | jsonify }}
> ```
> 
> Then you create a placeholder page in your content. `content/search/index.md` for example.
> 
> ```
> ---
> title: Search
> type: search
> ---
> 
> This is a placeholder to serve the search
> ```
> 
> Next you need to place the search field somewhere, maybe in the navbar:
> 
> ```
> <div class="navbar-item" role="search" id="search-wrapper">
>     <input type="search" class="input" placeholder="Search" autocomplete="off" id="search-field" disabled="disabled" />
> 
>     <div class="navbar-dropdown" id="search-results"></div>
> </div>
> ```
> 
> Then a little bit of JS to make it all click. You can copy the javascript.html template in your layouts and add it there.
> 
> ```
> <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
> <script src="https://unpkg.com/lunr/lunr.js"></script>
> <script>
> axios.get("/search")
>     .then(function (result) {
>         var searchContent = result.data;
>         var searchIndex = lunr(function () {
>             this.ref("id")
>             this.field("content");
>             this.field("tag");
>             this.field("title");
>             this.field("url");
> 
>             Array.from(result.data).forEach(function (doc) {
>                 this.add(doc)
>             }, this)
>         })
> 
>         var searchWrapper = document.getElementById("search-wrapper");
>         var searchInput = document.getElementById("search-field");
>         var searchResultElement = document.getElementById("search-results");
> 
>         searchInput.removeAttribute("disabled");
>         searchInput.addEventListener("keyup", function (e) {
>             var searchString = e.target.value;
>             if (searchString && searchString.length > 2) {
>                 try {
>                     searchResults = searchIndex.search(searchString);
>                 } catch (err) {
>                     if (err instanceof lunr.QueryParseError) {
>                         return;
>                     }
>                 }
>             } else {
>                 searchResults = [];
>             }
> 
>             searchWrapper.classList.add("is-active");
> 
>             if (searchResults.length > 0) {
>                 searchResultElement.innerHTML = searchResults.map(function (match) {
>                     var item = searchContent.find(function(e) {
>                         return e.id == parseInt(match.ref);
>                     });
> 
>                     return [
>                         "<div class='dropdown-item'>",
>                         "<h4><a href='" + item.url + "'>" + item.title + "</a></h4>",
>                         "<p>" + (item.content.length > 100 ? (item.content.substring(0, 100) + "...") : item.content) + "</p>",
>                         "</div>"
>                     ].join("");
>                 }).join("<hr class='navbar-divider'>");
>             } else {
>                 searchResultElement.innerHTML = '<div class="dropdown-item"><p>No results found</p></div>';
>             }
>         });
>     })
>     .catch(function (error) {
>         console.error(error);
>     });
> 
> </script>
> ```
> 
> Here I'm using axios for making the http request for the pre-built index, but the theme is using jQuery so I'd recommend to switch to that.
> Hope this helps.

Thanks。Ivan。Let me try.
