### ISSUE TITLE
Headings and newlines in .md file not rendered

### ISSUE THREAD

**Issue by infiniteNIL** [StefMa/hugo-fresh#117]
I created a new content page. Here's an example

```markdown
---
title: Contact Us
include_footer: true
---

infiniteNIL is a small software company, located in Sandy, Utah, a few minutes drive south from Salt Lake City.

We would very much like to hear from you. Please don't hesitate to contact us for any reason. If you need help with a product, have questions about a product, would like to see a new feature in a product, or just want to know more about us then just send us an email. You can fill out the form below or just send an email to support at this website.

support@infinitenil.com

## Spam is Evil

We hate spam as much as you do. Your contact info will never be shared, sold, or used for any purpose other than responding to your inquiry.

```

None of the blank lines are rendered and the Spam is Evil heading comes out as just plain text. Am I missing some kind of configuration or what could be causing this?

**Comment by StefMa** [comment]
Hi,

is this still an issue?
As far as I can see it [here](http://infinitenil.com/about-us/) everything works as expected, right?

**Comment by infiniteNIL** [comment]
That was awhile ago.It's actually here (http://infinitenil.com/about-us/)

I ended up working around it with just using HTML. It may have something to do with the CSS I was using (Using Tailwind CSS), which requires HTML for some of the styling.

**Comment by StefMa** [comment]
I just remembered that bulma (the css framework used in hugo-fresh), ignores h[1-6] html tags. The size of the font will be controlled via css attributes.

That is the reason why I introduced shortcodes.
Checkout the [agb page](https://github.com/StefMa/hugo-fresh/blob/73ded70a9730873fb9c23ceb17e28c2f41325c67/exampleSite/content/agb.md) as an example.

I hope this helps!
