### ISSUE TITLE
Question: how to add new layout?

### ISSUE THREAD

**Issue by maciekChmura** [StefMa/hugo-fresh#118]
First of all, thank you for creating this theme. I love it ❤️ 

I would like to add a new layout for single page. Small modification. Maybe just remove the title.
I followed tips in this thread but nothing seems to work for me.

https://discourse.gohugo.io/t/create-new-layout-for-an-about-page/6223

Could someone please help me figure it out?
Maybe someone has a working example?

Thanks.

**Comment by StefMa** [comment]
Please checkout this comment https://github.com/StefMa/hugo-fresh/issues/66#issuecomment-520350731

I hope this will help you to override the current layout.

**Comment by maciekChmura** [comment]
Thank you for your comment.
I am able to override the current layout, but can I have 2 layouts?

I would like to specify which layout to chose in markdown header file. Something like this:

file 1
+++
date = “2017-04-17T11:01:21-04:00”
draft = false
title = “Pricing”
layout = “pricing”
+++

file 2
+++
date = “2017-04-17T11:01:21-04:00”
draft = false
title = “About”
layout = “single”
+++

Can this be done?

**Comment by StefMa** [comment]
I am not sure with that. But I guess you need your own customer code to
realize that. It's not simply possibly by creating a new layout and then
let's Hugo pick it automatically.

**Comment by StefMa** [comment]
Closed as answered.
