### ISSUE TITLE
Can I deploy a hugo website with this themeto netlify?

### ISSUE THREAD

**Issue by davidbuenonnoleto** [StefMa/hugo-fresh#119]
I have been trying to deploy a hugo website with this theme to netlify, but it does not work

**Comment by StefMa** [comment]
Can you specify what do you mean with "it does not work"?

What's the error message?
Steps to reproduce and so on...

**Comment by davidbuenonnoleto** [comment]
so I created a new hugo website locally, then I added the theme as git submodule to my project, and when I run hugo serve on my root folder it works perfectly locally, but when I import the project from github to netlify, when I click on deploy I get the following page:
![Screen Shot 2021-02-08 at 12 47 06 PM](https://user-images.githubusercontent.com/2189246/107279425-e0955680-6a0b-11eb-8162-9e31b9f866b1.png)

**Comment by StefMa** [comment]
Hmm.. Unfortunately I can't help you here I guess.
If it's working locally then there might be an issue somewhere with
netlify. I don't use it so I can't give you proper support for that.
But since the outputs are only static files it should work on any web
provider nowadays.

**Comment by davidbuenonnoleto** [comment]
no worries @StefMa, anyways thanks for the help, I will see if I can get any support from the netlify side
