### ISSUE TITLE
How can I change the breakpoint at which the nav bar hamburger menu appears?

### ISSUE THREAD

**Issue by ksilz** [StefMa/hugo-fresh#125]
Hi,

It seems to kick in 1087 pixels or below. I'd like to lower this to, say, 900 or so. How can I do this?

**Comment by dfranco** [comment]
Hi @ksilz ,

Nav bar "hamburger" is defined here https://github.com/StefMa/hugo-fresh/blob/master/layouts/partials/navbar.html#L29

and nav bar burger documented at bulma.io here
https://bulma.io/documentation/components/navbar/#navbar-burger

again based on bulma.io documentation https://bulma.io/documentation/overview/responsiveness/#breakpoints

My guess is that nav bar burger appear if the screen is more than 769px.

Using the Sass flavor of Bulma.io might be a way to customise this.

Hope it helps

p.s: I'm not 100% sure, you'll have to test and check the documentation (I could be wrong)

**Comment by StefMa** [comment]
Closed because its answered.
In case you still have a question regarding this, don't hesitate to create a new issue.
