### ISSUE TITLE
How to create a new page (ex: Contact, List of blogs) in this theme?

### ISSUE THREAD

**Issue by DinaTaklit** [StefMa/hugo-fresh#127]
Hello, I want once I click on contact us on the navbar to lead me to contact us which should be a **new page**: I have created `contact.html` inside `themes/hugo-fresh/layouts` but did not work, I have tried many options but did not work for me. How should process? I do not want to have` contact.md` approach. any hint?

**Comment by StefMa** [comment]
Do you mean something like that https://hugo-fresh.vercel.app/blog/first?

Checkout the documenting here:
https://stefma.github.io/hugo-fresh/singlepage/

Does this help? 🤔

**Comment by DinaTaklit** [comment]
Nope, it does not, unfortunately. I want to create a new styled HTML page I do not want to use md file, what you shared is useful only for the privacy policy page, not a page that contains boxes and forms? I do not know how to manage this here

**Comment by StefMa** [comment]
You can simplt write HTML in the markdown files.

Closed as this has nothing to do with the theme itself...
