### ISSUE TITLE
Best way to hide page elements?

### ISSUE THREAD

**Issue by andrewimeson** [StefMa/hugo-fresh#13]
I'd like to hide certain page elements on the main page. I could modify the theme, but then I'd lose the easy upgrade path. Is there a way to hide elements via the YAML file? If I comment out `features:` and all children, the gray background still stays on the page.

I'd be happy to contribute docs if you can give me enough to figure it out 😄

**Comment by lucperkins** [comment]
@andrewimeson Unfortunately I don't really have the bandwidth to maintain this right now. Please feel free to submit a PR if you'd like to add a way of hiding/showing elements based on configuration.
