### ISSUE TITLE
failed to transform "style.sass" (text/x-sass): this feature is not available in your current Hugo version

### ISSUE THREAD

**Issue by jukefr** [StefMa/hugo-fresh#14]
I am running `Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-01T09:00:55Z`

I did the step by step in the README.md

When I try to `hugo server` I get

```
$ hugo server 
Building sites … ERROR 2018/08/06 15:57:05 error: failed to transform resource: TOCSS: failed to transform "style.sass" (text/x-sass): this feature is not available in your current Hugo version
Total in 15 ms
Error: Error building site: logged 1 error(s)
```

**Comment by jukefr** [comment]
my bad, thought I had the extended version installed, didn't.

you NEED hugo extended version, in my case `hugo_extended_0.46_Linux_64bit.deb`

**Comment by lucperkins** [comment]
@jukefr Glad to hear!

**Comment by insightcoder** [comment]
@jukefr I had the same issue.  Thanks!

**Comment by Zedonboy** [comment]
Am having the same issue with hugo 51 linux. any ideas?
