### ISSUE TITLE
Add banner at top of all pages

### ISSUE THREAD

**Issue by Elphikaus** [StefMa/hugo-fresh#147]
I am using this theme for a group website.

My director wants me to add a banner with a message to all visitors to the website.

Is there a Hugo/Fresh functionality that would allow this already?

Thanks

**Comment by StefMa** [comment]
Hey,

there is no default way to display a banner.

But you might want to have a look at bulma notification for this:
https://bulma.io/documentation/elements/notification/

**Comment by Elphikaus** [comment]
Hi,

Thanks, that was very helpful.

I would like to add a `notification` to the homepage.

Can I just add this in `/public/index.html`?

**Comment by StefMa** [comment]
Please make yourself familiar with how Hugo works under the hood.
You can simply fork this project and try out what you suggested and see if it works.
