### ISSUE TITLE
Customize the menu

### ISSUE THREAD

**Issue by raheems** [StefMa/hugo-fresh#15]
Hi,
I am wondering how to customize the menu such as the dropdown menu?

**Comment by lucperkins** [comment]
@raheems That's not currently customizable but I'll fix that.

**Comment by lucperkins** [comment]
@raheems Okay, I've updated it to allow for a customizable navbar. You can see how [here](https://github.com/lucperkins/hugo-fresh/blob/master/exampleSite/config.yaml#L28-L40).

**Comment by raheems** [comment]
The navbar-clone needs to reflect the changes as well 👍

**Comment by lucperkins** [comment]
Feel free to submit a pull request
