### ISSUE TITLE
Make documentation more prominent

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#159]
Currently it is a badge in the README.
This is invisible and should be changed somehow..

**Comment by StefMaIO** [comment]
I hope this is better now:
https://github.com/StefMa/hugo-fresh/blob/9dd0d7266b5cbfc927d73b296a94db3983c1f0a7/README.md 😅

**Comment by StefMa** [comment]
I hope this is better now 😅 
https://github.com/StefMa/hugo-fresh/blob/9dd0d7266b5cbfc927d73b296a94db3983c1f0a7/README.md
