### ISSUE TITLE
Any way to disable the loader animation?

### ISSUE THREAD

**Issue by nai888** [StefMa/hugo-fresh#163]
What would be the way to disable the loader animation that shows every time you navigate to a new page?

I do think it would be nice to have that animation any time a page is _actually_ taking a long time to load, but for simple, fast-loading pages, it seems to me that the animation is actually _delaying_ page navigation, and I'd like to get rid of it.

**Comment by StefMa** [comment]
Yes, it is possible.
Checkout https://github.com/StefMa/hugo-fresh/pull/140 how to do it...

Does this help?

**Comment by StefMa** [comment]
Documented via [this commit](https://github.com/StefMa/hugo-fresh/commit/039e31ef97b2f99465491fe53e61c6b59ec23dd3).

Will close it for now.
In case you have further questions, don't hesitate to ask again 👍

**Comment by nai888** [comment]
Aha! That did it! Thanks much!
