### ISSUE TITLE
How to override images

### ISSUE THREAD

**Issue by 4q1** [StefMa/hugo-fresh#165]
sorry, but the deployment instruction are lacking.  I have the example site up, but I try to change the illustrations/worker.svg logo, but it can't find my .svg in the static dir. worse, I can't find the file worker.svg anywhere, or images, or logos, etc.  all I have is a empty static dir.  Where are these files located and how can they be changed?

**Comment by StefMa** [comment]
hi @4q1,

thanks for using this theme.

By default, you don't get a "clean copy" of everything included from this theme on you file system.

If you want to override the `worker.svg` (or any other image), you have to place it on the exact location where it is in the theme, but on your file system.
The `worker.svg` for example is located at
[`static/images/illustrations/worker.svg`](https://github.com/StefMa/hugo-fresh/blob/f3620f5fb43dec31c548f7d996b18e062eac26ea/static/images/illustrations/worker.svg).
Now you can replace this image by creating (on your file system!) the same directory structure and the same name of the image.

Does this help? 🤔

**Comment by StefMa** [comment]
Will close this as answered.
In case you have more questions don't hesitate to ask.
