### ISSUE TITLE
Sidebar link not working

### ISSUE THREAD

**Issue by raheems** [StefMa/hugo-fresh#17]
Not exactly sure how the links in the sidebar menu are supposed to work. For me they do not work. 

I've inserted a link for the Profile of the User menu as follows. And the link doesn't work. Upon clicking, it closes the "User" menu.

sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: https://www.google.com
      - text: Account
        url: /
      - text: Settings
        url: /

**Comment by lucperkins** [comment]
@raheems That appears to be an issue with the [CSS Ninja theme](https://cssninja.io/themes/fresh) itself, which I do not maintain. So unfortunately I'm not really sure how to fix it.

**Comment by lucperkins** [comment]
I would encourage you, though, to see if there's a JavaScript fix in `fresh.js`.

**Comment by gfrenoy** [comment]
The fix in ```fresh.js``` is the following:

```
@@ -33,7 +33,7 @@ $(document).ready(function(){

     //Sidebar menu
     if ($('.sidebar').length) {
-        $(".sidebar-menu > li.have-children a").on("click", function(i){
+        $(".sidebar-menu > li.have-children > a").on("click", function(i){
             i.preventDefault();
             if( ! $(this).parent().hasClass("active") ){
                 $(".sidebar-menu li ul").slideUp();
```

So adding a ">" on line 36 so that only the root level of anchors react to a user click.

Let me submit a PR.
