### ISSUE TITLE
Issue integrating hugo-easy-gallery into hugo-fresh

### ISSUE THREAD

**Issue by jsacerot** [StefMa/hugo-fresh#170]
I want to generate some photo galleries for my ```hugo-fresh```-based website. I have tried to integrate [```hugo-easy-gallery```](https://github.com/liwenyip/hugo-easy-gallery) into ```hugo-fresh``` but have faced [some issues](https://github.com/liwenyip/hugo-easy-gallery/issues/82#issuecomment-1492818086) with the grid tile size and margin. It seems that the issue is related to [ an undocumented dependency on Bootstrap CSS v3.7.7](https://github.com/liwenyip/hugo-easy-gallery/issues/82#issue-1516019213). 

Do you have any ideas/suggestions on how to solve this issue? I would appreciate any help!

**Comment by Darthagnon** [comment]
@jsacerot It's probably a CSS issue - this theme uses advanced "SCSS" aka compiled CSS, which I have found difficult to work with. A suggestion, however, try putting the CSS for my fork of hugo easy gallery in your site root, perhaps with `!important` at the end of every CSS rule. What you're aiming to do is an override of this theme's styles, similar to [what I did for a friend's website using this other theme, Massively, that used SCSS](https://github.com/curtiscde/hugo-theme-massively/issues/116)

e.g.

```
my-cool-website
- themes
- - hugo-fresh
- content
- static
- - css
- - - hugo-easy-gallery.css
```

**Comment by jsacerot** [comment]
@Darthagnon Thank you for your suggestions. They were really helpful. I set ```!important``` at the end of every CSS rule, but it did not work. So, I decided to convert the CSS into a SASS using this [online app](https://css2sass.herokuapp.com/). There was a significant improvement (see screenshot below) compared to the [initial results](https://github.com/liwenyip/hugo-easy-gallery/issues/82#issuecomment-1492818086).  I still need to figure out how to make sure the tile spacing in the horizontal and vertical is the same.

![image](https://user-images.githubusercontent.com/57607681/229680601-5ec4d9a7-d5e8-4ce2-ae37-318a24e961d1.png)

**Comment by han16nah** [comment]
> @Darthagnon Thank you for your suggestions. They were really helpful. I set `!important` at the end of every CSS rule, but it did not work. So, I decided to convert the CSS into a SASS using this [online app](https://css2sass.herokuapp.com/). There was a significant improvement (see screenshot below) compared to the [initial results](https://github.com/liwenyip/hugo-easy-gallery/issues/82#issuecomment-1492818086). I still need to figure out how to make sure the tile spacing in the horizontal and vertical is the same.
> 
> ![image](https://user-images.githubusercontent.com/57607681/229680601-5ec4d9a7-d5e8-4ce2-ae37-318a24e961d1.png)

Cool. So you converted the `hugo-easy-gallery.css`? 
Where did you put the converted SASS file? Also in `static/css`? And did you save it as .sass?
Sorry, I do not have a lot of experience and would really like to get it working, so if you could give me some insight in how your file structure now looks like, that would be great!
