### ISSUE TITLE
Adding links to the section1 contents

### ISSUE THREAD

**Issue by raheems** [StefMa/hugo-fresh#18]
This not an issue but perhaps a request.

I would like to add links to the buttons in the section1 contents. For example, there are three blocks with buttons on each. If you could give an example of how to add links to them separately, that would be great.

The goal here is to showcase a list of books/articles which would link to the contents when clicked. 

I know you might not have free time for this request, and I completely understand that. Thanks.

**Comment by lucperkins** [comment]
Okay, I've added this 👍
