### ISSUE TITLE
Possible to have a second page in the same format of the home page?

### ISSUE THREAD

**Issue by firasm** [StefMa/hugo-fresh#185]
I'd like to create a second page that can be created the same way the home page (`hugo.yaml`) was created. 

Is that possible to do with this theme and Hugo ?

Would I need to use partials, or duplicate and create a new layout?

Any help and insight would be much appreciated.

Thanks!

**Comment by StefMa** [comment]
Hey,

not sure if I get it right, but if you want to have two times a "hero"
side, then I guess it is possible but would require a bit more work.

I guess you have to override the layout/index.html and inset a second
"hero-body". This should point to a "hero-body2.html" in partials. This is
basically a copy of "hero-body.html" with different names at the top.
Afterward it should be possible to use the new names in the config file...

**Comment by firasm** [comment]
Thanks!

That's perfect, exactly the direction I needed to solve the issue. 

Thanks for a great theme!
