### ISSUE TITLE
Can you provide a working project for theme?

### ISSUE THREAD

**Issue by rahulgawale** [StefMa/hugo-fresh#190]
I created a new project and copied this theme into the `themes` folder, and tried to run it. Now I am getting the below error.
Can you provide a full working example with a sample project?

Error: module "https://github.com/jgthms/bulma.git" not found; either add it as a Hugo Module or store it in "/mnt/d/KTL Website/quickstart/themes".: module does not exist

**Comment by StefMa** [comment]
Hey,

did you [see the docs](https://stefma.github.io/hugo-fresh/getstarted/)?
Did you see the [example site](https://github.com/StefMa/hugo-fresh/tree/master/exampleSite)?

Doesn't this work for you?
This theme has to be added as a hugo module. Not as a git submodule theme.

**Comment by rahulgawale** [comment]
Ahh, I couldn't find the documents earlier, but now I am good, really appreciate your help, thanks!
