### ISSUE TITLE
Is the installation procedure still up to date?

### ISSUE THREAD

**Issue by cip123** [StefMa/hugo-fresh#192]
I am following the guide from https://stefma.github.io/hugo-fresh/getstarted/

However, after running those steps, nothing happens. The themes folder is empty, and I get the following warnings:

```
WARN 2024/01/31 10:53:55 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/01/31 10:53:55 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/01/31 10:53:55 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

```
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.18.1"
```

**Comment by StefMa** [comment]
Yes, the guide should be up to date.
The themes folder is empty because it uses go modules under the hood. If you're interested in using the theme as git submodules then checkout this guide: https://stefma.github.io/hugo-fresh/deepmodifications/

It would also help if you can explain "nothing happen" a bit more. What do you see if you open http://localhost:1313 for example?

**Comment by cip123** [comment]
It was a blank page. But I managed to fix it. 

The problem is that `hugo.yaml` was not read. It might be that I have a newer Hugo version.

So, when I created the site, I specified that the configuration should be `yaml` 

`hugo new site eb-site -f "yaml"` 

And then, I copied the `Hugo.yaml` file to `config.yaml`.

**Comment by StefMa** [comment]
Nice! Thanks for the follow up.

But it is likely that you have rather an outdated version of Hugo 😉. Your [0.92 version](https://github.com/gohugoio/hugo/releases/tag/v0.92.0) is two years old.

**Comment by cip123** [comment]
Ah, ok. Thank you. It looks like Ubuntu repositories are not up to date.
