### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by invictus2010** [StefMa/hugo-fresh#193]
I am new to Hugo. I installed Hugo via Homebrew. I followed directions [here](https://stefma.github.io/hugo-fresh/getstarted/) to install hugo-fresh theme.

When I ran `rm config.toml` I got the message "No such file or directory. I proceeded with the rest of the steps in the instructions. Server started but just get a "Page Not Found" with no styling on localhost:1313.

What steps am I missing?

**Comment by StefMa** [comment]
Maybe you have the same problem like https://github.com/StefMa/hugo-fresh/issues/192 ? 🤔

**Comment by invictus2010** [comment]
ah yes very similar! I also got 
```
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

I then deleted and re-ran through the install again and noted the following discrepancies:

* On the command `hugo mod init <NAME>` I received `Error: failed to load modules: module "github.com/StefMa/hugo-fresh" not found in "/home/jwith/Projects/confident-controls/themes/github.com/StefMa/hugo-fresh"; either add it as a Hugo Module or store it in "/home/jwith/Projects/confident-controls/themes".: module does not exist`

* There was no `config.toml` file to remove
* On `hugo server` I received `Error: command error: failed to load modules: module "github.com/StefMa/hugo-fresh" not found in "/home/jwith/Projects/confident-controls/themes/github.com/StefMa/hugo-fresh"; either add it as a Hugo Module or store it in "/home/jwith/Projects/confident-controls/themes".: module does not exist`

hugo version = hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended linux/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=brew
go version go1.22.0 linux/amd64

**Comment by invictus2010** [comment]
re-did it and got `Error: command error: failed to load modules: module "github.com/jgthms/bulma" not found in "/home/jwith/Projects/confident-controls/themes/github.com/jgthms/bulma"; either add it as a Hugo Module or store it in "/home/jwith/Projects/confident-controls/themes".: module does not exist`

**Comment by StefMa** [comment]
Let me know if this issue is still present for you.
