### ISSUE TITLE
leading / on links to images causing deployment to sub paths not to load images 

### ISSUE THREAD

**Issue by unstableunicorn** [StefMa/hugo-fresh#202]
When deploying to gitlab pages, which uses a subpath e.g. `https://StefMa.gitlab.io/hugo-fresh/`, images would not load correctly.
This is caused by the leading `/` when referencing static files.
Changing references from:
`"/images/.../%s`
to
`"images/.../%s`

Should make it compatible with both site configurations.

Currently testing and will submit a PR shortly.

**Comment by StefMa** [comment]
Fixed via https://github.com/StefMa/hugo-fresh/pull/203.
And released with v1.1.0 https://github.com/StefMa/hugo-fresh/releases/tag/v1.1.0

Thanks again!

**Comment by unstableunicorn** [comment]
> Fixed via #203. And released with v1.1.0 https://github.com/StefMa/hugo-fresh/releases/tag/v1.1.0
> 
> Thanks again!

Awesome! Glad I could help a little :)
