### ISSUE TITLE
Canot init site

### ISSUE THREAD

**Issue by liufuyang** [StefMa/hugo-fresh#204]
Hi there, thanks for the good work.

I am trying to use this theme the first time by following this guide
https://stefma.github.io/hugo-fresh/getstarted/

And this is what I get after doing `hugo server`

```
Start building sites …
hugo v0.125.5+extended darwin/arm64 BuildDate=2024-05-01T15:22:11Z VendorInfo=brew

Built in 21 ms
Error: error building site: render: failed to render pages: render of "home" failed: "/Users/fuyangl/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!stef!ma/hugo-fresh@v1.0.0/layouts/_default/baseof.html:4:7": execute of template failed: template: index.html:4:7: executing "index.html" at <partial "meta.html" .>: error calling partial: execute of template failed: html/template:partials/meta.html:1:12: no such template "_internal/google_analytics_async.html"
```

Perhaps you can help give some tips? Thanks :)

**Comment by StefMa** [comment]
You run probably in https://github.com/StefMa/hugo-fresh/issues/195.

Can you checkout the latest hash of the theme and see if it works?

I might do a release the next days and then thus issue should be gone...

**Comment by liufuyang** [comment]
Aha, how to check with the latest hash?

**Comment by liufuyang** [comment]
Oh right, I did this `go get github.com/StefMa/hugo-fresh@100f20abd767b76a4bbb0d4764519dd26ec41f01`, then the reference in go.mod is updated. Then it can work with the latest hash. 

Thanks a lot, feel free to close this issue anytime :)

**Comment by PepperPlatypus** [comment]
@liufuyang it did solve the issue, but shouldn't the documentation be updated here https://stefma.github.io/hugo-fresh/getstarted/ before closing ?

**Comment by StefMa** [comment]
I will create a new release this week. Then this issue shouldn't be
documented somewhere and is solved automatically.

**Comment by StefMa** [comment]
v1.1.0 is out.
See https://github.com/StefMa/hugo-fresh/releases/tag/v1.1.0

This issues is obsolete now. Going to be close it.
