### ISSUE TITLE
bulma is removed but still being imported

### ISSUE THREAD

**Issue by wrfly** [StefMa/hugo-fresh#205]
https://github.com/StefMa/hugo-fresh/blob/100f20abd767b76a4bbb0d4764519dd26ec41f01/assets/style.sass#L1

bulma had been removed in this commit https://github.com/StefMa/hugo-fresh/commit/c6652ee7f6a494dba8155a43ad2395d2dd115f8f

```
Error: error building site: TOCSS: failed to transform "/style.sass" (text/x-sass): "xxxx/_vendor/github.com/StefMa/hugo-fresh/assets/style.sass:1:1": File to import not found or unreadable: bulma/bulma.
```

**Comment by StefMa** [comment]
Hey,

can you please explain what do you mean by that issue? I don't get.
Do have any issue you are facing?

**Comment by wrfly** [comment]
Hi stefma,

when I trying to build, hugo reports an error `File to import not found or unreadable: bulma/bulma.`

I traced the git commit, and found that this package had been removed many years ago, but it still been imported in the [style.sass](https://github.com/StefMa/hugo-fresh/blob/100f20abd767b76a4bbb0d4764519dd26ec41f01/assets/style.sass#L1) file 

hugo version: `hugo v0.125.6-69ede10edcd539380914bbee58d4d32953dd8b43+extended linux/amd64 BuildDate=2024-05-05T10:52:52Z VendorInfo=gohugoio`

**Comment by StefMa** [comment]
Did you followed the instructions here https://stefma.github.io/hugo-fresh/getstarted/?

**Comment by wrfly** [comment]
yes, that's for sure

**Comment by StefMa** [comment]
Same/similar as https://github.com/StefMa/hugo-fresh/issues/206.
Going to close this.
Probably not an problem
