### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by wrfly** [StefMa/hugo-fresh#206]
I'm using the latest code, but failed to build the website

![image](https://github.com/StefMa/hugo-fresh/assets/7827389/6f267c6b-c05a-4ee6-97fb-eb4bab82f5d6)

**Comment by StefMa** [comment]
Hey,

could you please let me know how do you install/setup the theme?
Maybe this helps to investigate the problem you are facing.

**Comment by wrfly** [comment]
Yes, sure

here is my steps:

1. install the latest hugo-extended version from https://github.com/gohugoio/hugo/releases
2. init a hugo site with `hugo new site xxx`
3. follow the steps in the document here https://stefma.github.io/hugo-fresh/getstarted/
4. found that the [hugo-fresh/assets/style.sass](https://github.com/StefMa/hugo-fresh/blob/100f20abd767b76a4bbb0d4764519dd26ec41f01/assets/style.sass#L1) is incorrect and hugo cannot build
5. remove the first line of it (`@import "bulma/bulma"`) from `_vendor/github.com/xxxx`
6. run `hugo server`

**Comment by StefMa** [comment]
If I left out step 4, everything works as expected for me.
used `v0.110.0+extended`

**update**
Also tested with the latest verison `hugo v0.126.1+extended darwin/arm64 BuildDate=2024-05-15T10:42:34Z VendorInfo=brew`.
Don't have any issues.

**Comment by StefMa** [comment]
Closed as everything works as expected.
You might have an issue somewhere else...
