### ISSUE TITLE
Replace `.Site.IsServer` with `hugo.IsServer`

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#207]
Running with the latest hugo version (hugo v0.126.1+extended) reveals:

> WARN  deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in a future release. Use hugo.IsServer instead.

**Comment by jaystern** [comment]
This is now showing as 'ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.134.0. Use hugo.IsServer instead.' and failing to build for a clean install on MacOS of go and Hugo.

go version: go version go1.23.0 darwin/arm64
Hugo version: hugo v0.133.0+extended darwin/arm64 BuildDate=2024-08-17T19:57:41Z VendorInfo=brew

Seems like the file causing the error is hugo-fresh/layouts/partials/css.html. Changing the line to be '{{- $inServerMode := hugo.IsServer }}' works for me.

But I'm not sure if it is required to handle both the new case and the old case. The mainroad theme had a recent commit that might help handle both the old and new cases: https://github.com/Vimux/Mainroad/commit/86f1b1987c68ebe429be3e9e801af6dbb98d2d0c 

Thanks for a great theme!
