### ISSUE TITLE
duplicate ids error

### ISSUE THREAD

**Issue by rickb777** [StefMa/hugo-fresh#21]
Your theme generates badly-formed HTML with several duplicate ids. These are not allowed by W3C specs.

For example in index.html
id="menu-icon-wrapper"
id="menu-icon-trigger"

**Comment by rickb777** [comment]
It seems these can simply be deleted from the source templates without affecting the javascript code.

**Comment by lucperkins** [comment]
@rickb777 This theme is just a Hugo wrapper around someone else's logic. Is there a visual issue here or just a spec issue?

**Comment by StefMa** [comment]
Hi @rickb777 
can you please give us an update here and answer the question from @lucperkins ? :)

**Comment by StefMa** [comment]
Closed due inactivity...
