### ISSUE TITLE
Please make Hugo Fresh work for all versions of Hugo.

### ISSUE THREAD

**Issue by onedrawingperday** [StefMa/hugo-fresh#22]
Hello @lucperkins 

This came up in the Hugo forum today: https://discourse.gohugo.io/t/hugo-fresh-a-wonderful-theme-for-learning-new-hugo-features/13792/2 from a user who tried to use your theme without having installed Hugo Extended.

Recently a decision was made that Hugo themes assets should be considered as stable and theme authors who use Hugo Extended features should commit their `/resources/` directory so that a theme works in all versions of Hugo. See [here](https://github.com/gohugoio/hugoThemes/issues/396) for the relevant discussion.

Can you please look into it? 

Thank you very much!

CC / @digitalcraftsman

**Comment by lucperkins** [comment]
@onedrawingperday Can I simply put the generated `resources` directory in the theme? I've only ever used the `resources` directory in the main project directory.

**Comment by lucperkins** [comment]
@onedrawingperday I've now added the `resources` directory. As far as I know this *should* work. I'm closing this issue for now. Please feel free to re-open if there are further issues.

**Comment by onedrawingperday** [comment]
Thanks so much for the swift reply!

**Comment by mojoa** [comment]
Can we re-open this issue? Extended version of Hugo is needed to use the theme currently. 
Hugo Topic: https://discourse.gohugo.io/t/hugo-extended-needed-for-hugo-fresh-theme/13844/22
Thank You

**Comment by lucperkins** [comment]
@mojoa I’m sorry, but I do not plan on making this theme compatible with non-extended versions of Hugo. That would involve setting up a parallel Sass-to-CSS conversion pipeline that I would really prefer not to create. Others are welcome to add that via pull request if they wish.

**Comment by mojoa** [comment]
Would it be possible to update the instructions to include mention of this dependency? The current step by step is perfect except the end result is a somewhat cryptic error if the user is not aware they need Hugo Extended.

**Comment by lucperkins** [comment]
Oh sure, that’s no problem. I can do that tomorrow.

**Comment by mojoa** [comment]
Just wondering if you were still planning on updating..

**Comment by lucperkins** [comment]
As far as I can tell there’s no need for an update here. The theme will work without the extended version of Hugo as demonstrated on the discussion board.

Follow these exact steps:

```shell
hugo new site my-site && cd my-site
git clone https://github.com/lucperkins/hugo-fresh themes/hugo-fresh
rm config.toml
curl -O https://raw.githubusercontent.com/lucperkins/hugo-fresh/master/exampleSite/config.yaml
hugo server
```

If that doesn't work for you then I really don't know what to tell you. I just tried it out with a non-extended version of Hugo.

**Comment by mojoa** [comment]
The single person who claims it works without the extended version can not explain why it actually does not work. Others state you need it. I am simply spinning up a VM (fedora 28), downloading the Hugo binary and following the instructions listed for your Theme by copying the lines verbatim. Does it work for you without the extended Hugo? It should take you less than 5 minutes to verify what I am saying.. I may be wrong and would love to know. Regards,

**Comment by lucperkins** [comment]
It works for me without an extended version of Hugo. I’ve tested it with multiple non-extended versions.

**Comment by mojoa** [comment]
Wow, OK.. I am assuming this started working only after you "put the generated resources directory in the theme" ..  I never got a definitive confirmation from anyone that this change made it possible to use standard Hugo.

**Comment by lucperkins** [comment]
Yes, that is correct. An issue was reported and I fixed it so that the theme would work with standard Hugo. Sorry for the lack of confirmation.

**Comment by mojoa** [comment]
Finally got around to testing this and unfortunately hugo standard does not work.
I launched a new AWS ec2 instance and downloaded the latest Hugo version.
wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
Installed Hugo in /usr/local/bin/ 
-# which hugo
/usr/local/bin/hugo
-# hugo version
Hugo Static Site Generator v0.48 linux/amd64 BuildDate: 2018-08-29T06:33:51Z
And followed your published directions starting with:
-# hugo new site my-site && cd my-site
Congratulations! Your new Hugo site is created in /root/hudl/my-site.
-# git clone https://github.com/lucperkins/hugo-fresh themes/hugo-fresh
 rm config.toml
-# curl -O https://raw.githubusercontent.com/lucperkins/hugo-fresh/master/exampleSite/config.yaml
Result:
-# hugo server
Building sites … ERROR 2018/09/07 15:32:06 error: failed to transform resource: TOCSS: failed to transform "style.sass" (text/x-sass): this feature is not available in your current Hugo version
Total in 20 ms
Error: Error building site: logged 1 error(s)
I have also tested on a brand new fedora 28 VM with the same result.
I downloaded and installed the hugo extended version and replaced the standard hugo binary in /usr/local/bin and the server launched no problem.
-# hugo version
Hugo Static Site Generator v0.48/extended linux/amd64 BuildDate: 2018-08-29T06:57:35Z

Any ideas?

**Comment by lucperkins** [comment]
@mojoa I guess you're just going to have to use the extended version. This may not be a resolvable issue.

**Comment by mojoa** [comment]
Thanks,
It might me nice if you let users know by updating your succinctly written step-by-step installation instructions to mention the requirements of having to use Hugo Extended. My goal is to keep others from spending time like I have, trying the standard Hugo, thinking it should work. 

https://themes.gohugo.io/hugo-fresh/

**Comment by lucperkins** [comment]
@mojoa Please submit a pull request with those changes
