### ISSUE TITLE
Pipeline not Re-Compiling After Changes

### ISSUE THREAD

**Issue by CelticParser** [StefMa/hugo-fresh#23]
Hi, can you take at look at the issue I am having on the Hugo Community site?  I'd appreciate it!

I think I'm just missing something but haven't traced it down yet

[https://discourse.gohugo.io/t/pipeline-not-re-compiling-after-changes/13889](https://discourse.gohugo.io/t/pipeline-not-re-compiling-after-changes/13889)

**Comment by lucperkins** [comment]
@CelticParser I took a look yesterday and AFAICT that issue is not specific to this theme.

**Comment by StefMa** [comment]
Closed as answered
