### ISSUE TITLE
CSS missing from Demo on Hugo Site

### ISSUE THREAD

**Issue by onedrawingperday** [StefMa/hugo-fresh#24]
Hello again @lucperkins 

Today it was reported in the forum that your theme demo is [broken](https://discourse.gohugo.io/t/hugo-fresh-a-wonderful-theme-for-learning-new-hugo-features/13792/4). 

I have seen a similar case when I was [reviewing](https://github.com/gohugoio/hugoThemes/issues/395#issuecomment-409029194) the Hugo Tale theme for the Themes Site.

If you view the source of your theme's [demo](https://themes.gohugo.io/theme/hugo-fresh/) on the Hugo Site, you will see that on lines 12 and 15 your `CSS` has the wrong permalink. It seems that for assets published through Hugo Pipes `.Permalink` renders an absolute URL and `.RelPermalink` produces the correct one.

To fix this problem in your `partials/css.html`please do the following:

- First change [line 12](https://github.com/lucperkins/hugo-fresh/blob/master/layouts/partials/css.html#L12) to: `<link rel="stylesheet" type="text/css" href="{{ $css.RelPermalink }}">`

- Then change [line 15](https://github.com/lucperkins/hugo-fresh/blob/master/layouts/partials/css.html#L15) of your `partials/css.html` to:
`<link rel="stylesheet" type="text/css" href="{{ $css.RelPermalink }}" integrity="{{ $css.Data.Integrity }}">`

I have tested the above fixes with the Themes Site Build Script and once you do the above your demo will once again be generated with its CSS, (once the Hugo Site is updated).

---
CC / @digitalcraftsman

**Comment by lucperkins** [comment]
@onedrawingperday Fixed! Thanks a lot for your very speedy and thorough help!!! Excellent way to do open source 👍
