### ISSUE TITLE
Include and link normal hugo pages in theme?

### ISSUE THREAD

**Issue by chbndrhnns** [StefMa/hugo-fresh#25]
I would like to add a privacy policy, for example. How would I embed that as a page in Hugo? I do not want to mix my content with the theme so I tried `hugo new privacy`, ended up with that md file but I am not sure how I can create another html template that is rendered with the hello-fresh theme.

Would you maybe give me a hint on that one?

**Comment by lucperkins** [comment]
@chbndrhnns I'd recommend consulting the Hugo documentation on sections, as you'd need to add a section template for that to work. This theme only has a main page template and thus can't yet accommodate adding additional pages.

**Comment by StefMa** [comment]
HI @chbndrhnns 

I think this is solved with #35.
I hope I can show you an example in #54 and #50 which will then fit your requirements 👍

**Comment by StefMa** [comment]
@chbndrhnns #54 is fixed.
I'll close this for now. If you have any questions feel free to comment here again 👍
