### ISSUE TITLE
section3 image overlaps section2 feature illustrations

### ISSUE THREAD

**Issue by nickray** [StefMa/hugo-fresh#27]
On half-width window on desktop, it seems that section3 overlays section2:

![image](https://user-images.githubusercontent.com/1092423/45933955-4269d880-bf97-11e8-9019-0e57c109f561.png)

Any idea what's causing this?

**Comment by nathanbiller** [comment]
This isn't an elegant fix (nor is the proper one), but it does fix the overlapping issue for the desktop view (the smaller iPad view is still messed up and the mobile view has extra space in it), but it's a short term fix until the proper fix is done somewhere within the css classes.

Copy section3.html to your partials folder and then open up the html in your favorite text editor.

Starting on line 6 add-in seven <br> tags which will add in enough line breaks to move the image down. 

So it should look like this:
```
{{- $buttonLink := index $section3 "buttonlink" }}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<section class="section section-feature-grey is-medium">
```
I'd love to get this resolved within the CSS code as it's not a great solution; unfortnately my skills aren't good enough to allow me to fix this yet :(

**Comment by nathanbiller** [comment]
@nickray Pretty sure I was able to figure this out; I've created a pull request after testing on my site and everything seems to work. If @StefMa approves and merges you won't need my clumsy workaround above, everything should just work as expected :)

**Comment by nickray** [comment]
He, thanks for looking at this. The site I was using the theme for no longer uses it though 😉
