### ISSUE TITLE
unable to get theme to deploy per Hugo instructions

### ISSUE THREAD

**Issue by Allen616** [StefMa/hugo-fresh#3]
Theme has been downloaded, but when I go to http://localhost:1313, nothing appears. I am getting the below error in terminal:

ERROR 2018/04/15 19:05:45 Error while rendering "home" in "": template: /Users/allen/Sites/Allen616/clFresh/themes/hugo-fresh/layouts/index.html:6:7: executing "/Users/allen/Sites/Allen616/clFresh/themes/hugo-fresh/layouts/index.html" at <partial "css.html" .>: error calling partial: template: theme/partials/css.html:4:12: executing "theme/partials/css.html" at <.Site.IsServer>: can't evaluate field IsServer in type *hugolib.SiteInfo

**Comment by lucperkins** [comment]
Which version are you using? I believe you’ll need 0.38.2 or later.

**Comment by lucperkins** [comment]
I’ll update the theme config to reflect that

**Comment by Allen616** [comment]
I have used the most recent commit, without luck. Thx

**Comment by lucperkins** [comment]
Which version of Hugo are you using?

**Comment by Allen616** [comment]
Have updated to Hugo 38.2. Getting following error.

Building sites … ERROR 2018/04/15 22:42:22 Error while rendering "home" in "": template: /Users/allen/Sites/Allen616/clFresh/themes/hugo-fresh/layouts/index.html:6:7: executing "/Users/allen/Sites/Allen616/clFresh/themes/hugo-fresh/layouts/index.html" at <partial "css.html" .>: error calling partial: template: theme/partials/css.html:5:36: executing "theme/partials/css.html" at <index .Site.Data.ass...>: error calling index: index of untyped nil

**Comment by Allen616** [comment]
I have updated to Hugo 3.9. After initial addition of theme, I do not get an error from Hugo when running server. Attached is the code viewed from the browser.

![hugo-fresh](https://user-images.githubusercontent.com/13263983/38812301-f2b74180-4159-11e8-93b0-1fb9bf031420.png)

**Comment by sashker** [comment]
Hello!

The same is for me in the macOS/3.9 version.

**Comment by jalbertocoder** [comment]
Hi @Allen616 and @sashker.
If you are having 'Error while rendering "home" in "": template: ...' I am pretty sure is because something went wrong with the building process. 
Make sure you don't have the node_modules folder into the directory that wraps your template into the themes folder, then from the console type ```cd <path_of_your_hugo_project>/themes/<name_of_your_template_folder>``` and then from here type ```make setup``` and ```make build``` those command will create the node_modules again.
After that when you run ```hugo server -D``` it should work
@lucperkins probably you couldn't replicate it because you already have those node dependencies in your local machine, but I am pretty sure you will if you delete them. In that case I think we can prevent this in the future by detailing it in the documentation

**Comment by MrZoidberg** [comment]
same problem. make setup and make build didn't help.

**Comment by ursuad** [comment]
It seems that after you do a:
* `make dev` 
* stop the Hugo server
* start it gain 

seems to work. This is just a quick workaround. Maybe @lucperkins can push a fix.  I don't have time to debug this further, but as far as I see, during the `make dev` phase, this two files were generated:
```
js/fresh-0cb1e7fa.js
css/core-b2ba1310.css
```

**Comment by vpnels** [comment]
Have been trying also to get this up and running. I followed the advices above. I am getting the following error:
ERROR 2018/04/17 20:09:18 Error while rendering "home" in "": template: /Users/Pascal/workspace/hugo/test/layouts/index.html:6:7: executing"/Users/Pascal/workspace/hugo/test/layouts/index.html" at <partial "css.html" .>: error calling partial: template: partials/css.html:5:36: executing "partials/css.html" at <index .Site.Data.ass...>: error calling index: index of untyped nil

**Comment by warent** [comment]
I'm having the same problem, and @ursuad is right. I went into the folder, ran `npm i` and `make dev`, had to close out of the js:watch gulp task, then went back to project root, ran the server, and now the error is gone.

**Comment by jalbertocoder** [comment]
Hi @warent I saw your original message. Did you realise it is not empty? you need to replace the root's config file

**Comment by lucperkins** [comment]
@Allen616 @warent @vpnels I've updated the README with new instructions
