### ISSUE TITLE
Some images in the mobile browser do not work

### ISSUE THREAD

**Issue by fra42** [StefMa/hugo-fresh#4]
Hi there!

I tried the site demo on the Hugo site but some images are missing..  here a screenshot https://ibb.co/fUZVHS

Thanks a lot!

**Comment by fra42** [comment]
Update: It seems a Firefox problem. Tried with both Firefox Nightly and Firefox Focus.

Also, some images di not display in Firefox Nightly for desktop too...

**Comment by lucperkins** [comment]
This theme is a pure port of the CSS Ninja Fresh theme, which I did not design myself, so I unfortunately can't really offer any help on browser-specific issues. Sorry.
