### ISSUE TITLE
Button text style issue

### ISSUE THREAD

**Issue by lina2358** [StefMa/hugo-fresh#40]
```html
        <div class="field is-horizontal">
          <div class="field-body">
            <div class="field">
              <div class="control">
                <button type="submit" class="button cta rounded primary-btn raised">Enviar mensaje</button>
              </div>
            </div>
          </div>
        </div>
```
results in 
![image](https://user-images.githubusercontent.com/31328370/50794650-b22b7700-1299-11e9-83ba-690a569670fa.png)

The (aparently) offending part is `cta`class with
```scss
// _button.scss
        padding: 26px 40px 26px 40px;
```

I've not found a way to make this work. (Chrome: Versión 71.0.3578.98 (Build oficial))

**Comment by lina2358** [comment]
[This](https://stackoverflow.com/questions/6007469/why-are-these-two-buttons-rendering-different) led to the solution.

**Comment by StefMa** [comment]
Hi @acl2358 
can you please give me the file where this html code can be found?
