### ISSUE TITLE
Clipart SVG Source/License?

### ISSUE THREAD

**Issue by cliffordh** [StefMa/hugo-fresh#47]
Hi, I'm interested in using the SVG of the woman at her desk and also finding other licensable artwork in the same style. Where is the artwork from?

**Comment by StefMa** [comment]
Hi @cliffordh 

I can't answer to that. Sry :(
I've taken the project from @lucperkins 
Maybe we can answer to it?

**Comment by StefMa** [comment]
Because this Hugo theme is basically a port of [this fresh](https://cssninja.io/themes/fresh#) and this is licenses under the [MIT](https://github.com/cssninjaStudio/fresh/blob/master/License) you are basically "free" to use the svgs.
