### ISSUE TITLE
Add additional pages, blog, services etc..

### ISSUE THREAD

**Issue by digitaldissent** [StefMa/hugo-fresh#57]
I would like to be able extend the theme to include other types of pages—blog posts, documentation pages, etc.

Is it possible to provide instructions or a a sample for one to follow?

Thanks

**Comment by StefMa** [comment]
It is already possible to create single pages. See this PR for more
information:
https://github.com/StefMa/hugo-fresh/pull/35

Does this help?
Unfortunately I don't have a sample for that yet...
See also #54

**Comment by StefMa** [comment]
I hope #58 explains it well.
If not feel free to ask again :)
