### ISSUE TITLE
Layout broken on fresh install

### ISSUE THREAD

**Issue by sbmueller** [StefMa/hugo-fresh#61]
When I follow the instructions precisely, I can't manage for the site to be deployed correctly. When I run `hugo server` I get the following warnings:
```
Building sites … WARN 2019/06/25 16:07:54 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/06/25 16:07:54 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```
When accessing the page, it looks very broken:
![image](https://user-images.githubusercontent.com/7465688/60105555-cee23b00-9763-11e9-82ab-9fe905a9a18b.png)

Hugo version:
```
Hugo Static Site Generator v0.55.6-A5D4C82D2/extended darwin/amd64 BuildDate: 2019-05-18T08:06:24Z
```
Go version:
```
go version go1.12.6 darwin/amd64
```
Latest hugo-fresh from Github, MacOS 10.14.5.

**Comment by SofianeBoumedine** [comment]
Hi I have the same error on Ubuntu 16.0.4.

**Comment by StefMa** [comment]
I see the same **WARNING**.
But my layout isn't broken.

Can you please checkout the HTML source code and say where it try to look at the `css` file? 
Thanks 🆗

**Comment by sbmueller** [comment]
I could solve the problem by deleting my browser cache. Feel free to reopen if the issue persists for you.
