### ISSUE TITLE
Setup section5 with getform (to send emails)

### ISSUE THREAD

**Issue by ghost** [StefMa/hugo-fresh#66]
Hi,

I activate section5 by "true", but then I don't find where to setting up to make it work with service like getform.

Thank you for your work!

**Comment by StefMa** [comment]
Hi @s6nougat 

I'm not 100 percent sure if this will work (but according to the [Hugo documentation](https://gohugo.io/templates/partials/) I think it will).
But you could create a file called `section5.html` inside the directory `layouts/partials`.
You can use [*this* file](https://github.com/StefMa/hugo-fresh/blob/09cd890f5ca51dfd97f5dc15874d198816003f29/layouts/partials/section5.html) as a template and replace the form with your [getform](https://getform.io/) information.

If you give it try I would like to receive a feedback if it work 👌

**Comment by ghost** [comment]
Getform works perfectly using your template section5.hmtl I just have to make some layout ajustment. 

Thank you very much for your help!

**Comment by StefMa** [comment]
Awesome. Thank you for the feedback 👍

**Comment by nathanbiller** [comment]
Just in case anyone else stumbles upon this issue: if you deploy/host with Netlify after copying section5.html to your partials override folder as described above you just need to add ```"data-netlify="true" method="POST"``` to your ```<form name="contact">``` and on build they'll automatically inject the ability to handle submissions and you can set them up to go directly to Slack or e-mail :)
