### ISSUE TITLE
Footer should be optional

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#67]
See https://github.com/StefMa/hugo-fresh/issues/48#issuecomment-524524762

**Comment by imawhale** [comment]
Footer is optional. Remove the shortcode from the page (eg. index.html).

**Comment by StefMa** [comment]
It already behaves like this.
https://github.com/StefMa/hugo-fresh/blob/0c2ca44b94ef496cbabadefa32685feebd596a17/layouts/index.html#L26-L28
It only reenders the footer in case its available in the config.

Works similar on single pages.
https://github.com/StefMa/hugo-fresh/blob/0c2ca44b94ef496cbabadefa32685feebd596a17/layouts/_default/single.html#L20-L22
