### ISSUE TITLE
Don't relay on alpine hugo version

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#81]
We have some issues with hugo and our CI.
See [this comment](https://github.com/StefMa/hugo-fresh/pull/76#issuecomment-538325216) (and the whole PR) for more information.

Our CI should download a fixed version of hugo instead of relaying on the version which are bundles with alpine linux...

**Comment by nathanbiller** [comment]
Hugo releases are available in multiple formats here: https://github.com/gohugoio/hugo/releases
