### ISSUE TITLE
Main navigation is broken

### ISSUE THREAD

**Issue by todinov** [StefMa/hugo-fresh#85]
It looks like this pull request https://github.com/StefMa/hugo-fresh/pull/78/files broke the main navigation. As far as I understand the idea was to fix hugo warnings by replacing .URL with .Permalink in the templates, but only one of those replacements was needed. The others were attributes in the config file.

**Comment by StefMa** [comment]
Can you please give more insites "whats broken"?
I don't understand the issue...
Maybe an example would be great 👍

**Comment by nathanbiller** [comment]
@todinov I agree more details would be helpful. I basically just did a find/replace for .URL and .Permalink 

There were multiple warnings that I was trying to address. I probably could have made this more clear by doing two separate PRs, but I combined them.

Reviewing those changes I noticed in layouts/partials/single/sidebar.html Line 11 the following changes which I don't recall why I would have changed this. If there's an error you can help us understand, I'm guessing that this is the likely culprit. I've disabled the sidebar on my site, so that's not something I would immediately notice if I inadvertently broke. Sorry about that!

```
      {{ range where .Site.RegularPages "Section" (strings.TrimSuffix "/" .Dir) }}
      {{ range where .Site.RegularPages "Section" (strings.TrimSuffix "/" .File.Dir) }}
```

**Comment by todinov** [comment]
I'm sorry, I should have been more specific. I'm actually talking about the main navigation (navbar.html and navbar-clone.html). You can see that in the pull request I referenced, the navbar was changed to use .Permalink in this section:

```
<div class="navbar-end">
  {{- range $navbar }}
  {{- if .sublinks }}
  <div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link">
      {{ .title }}
    </a>

    <div class="navbar-dropdown">
      {{- range .sublinks }}
      <a href="{{ .Permalink }}" class="navbar-item">
        {{ .title }}
      </a>
      {{- end }}
    </div>
  </div>
  {{- else if .button }}
  <a href="{{ .Permalink }}" class="navbar-item">
    <span class="button signup-button rounded secondary-btn raised">
      {{ .title }}
    </span>
  </a>
  {{- else }}
  <a href="{{ .Permalink }}" class="navbar-item is-secondary">
    {{ .title }}
  </a>
  {{- end }}
  {{- end }}
</div>
```
There is no Permalink in this context, because $navbar is defined as:
```
{{- $navbar := .Site.Params.navbar }}
```
This means that we are just looping through the navbar configuration in config.yaml, which is not an array of page objects. This means that this should have been kept as .url, because links in navbar are defined:
```
  navbar:
  - title: Home
    url: /
```
The result is that the href attributes are empty. I guess it's not obvious that it doesn't work when using the example configuration, because there all the links are defined as `url: /`, but I'm not sure why you are not seeing it in your website (unless you have overriden the navbar).

**Comment by nathanbiller** [comment]
Ah, yes that's exactly what I did (over road my navbar so that my logo could display larger). Sorry about that. I was trying to help and inadvertently made things worse :(
