### ISSUE TITLE
Does not work with JavaScript disabled

### ISSUE THREAD

**Issue by localguru** [StefMa/hugo-fresh#9]
Hi,

the theme is not working with JavaScript disabled (eg. NoScript Add-on), just a blank site with the loading icon displayed.

Ciao!

**Comment by lucperkins** [comment]
I unfortunately don’t really have the bandwidth to update this project, so please feel free to submit a pull request if you run into issues

**Comment by viaoi** [comment]
Building sites … ERROR 2018/08/01 10:27:16 Error while rendering "home" in "": template: index.html:6:7: executing "index.html" at <partial "css.html" .>: error calling partial: template: partials/css.html:5:36: executing "partials/css.html" at <index .Site.Data.ass...>: error calling index: index of untyped nil
Total in 5 ms
Error: Error building site: logged 1 error(s)

**Comment by lucperkins** [comment]
@aigitech Please follow the instructions in the README.

**Comment by lucperkins** [comment]
@viaoi Please follow the instructions in the README

**Comment by lucperkins** [comment]
@localguru I don't really have any plans to adapt the theme to work without JavaScript. Please feel free to submit a pull request if you'd like to add support for that.
